# Describes the format for available Blink services

event_websocket_command:
  description: Send websocket commands to the loxone server. More infos and commands https://www.loxone.com/dede/kb/api/
  fields:
      uuid:
        description: Uuid for device which you want to send a command
        example: 0f1e0b31-0178-7f77-ffff402fb0c34b9e
      value:
        description: Command which you want to send
        example: pulse